name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Do a dry run to preview instead of a real release'
        required: true
        default: 'true'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Fetch
        run: git fetch --prune --unshallow --tags

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          package-manager-cache: false

      - name: Setup Yarn
        run: npm install -g yarn@1.22.22

      - name: Install
        run: YARN_IGNORE_PATH=1 yarn install --frozen-lockfile

      - name: Verify
        run: |
          npm run typescript
          npm run lint

      - name: Test
        run: npm test

      - name: Configure Git User
        run: |
          git config --global user.name amplitude-sdk-bot
          git config --global user.email amplitude-sdk-bot@users.noreply.github.com

      - name: Release (Dry Run)
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release -- --dry-run --ci --no-npm.publish --npm.skipChecks

      - name: Release
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release -- --ci --no-npm.publish --npm.skipChecks
