name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20', '22']
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Cache Node Modules
      uses: actions/cache@v5.0.5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v6.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: yarn

    - name: Build (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: CURRENT_ARCH=arm64 yarn

    - name: Test
      run: yarn test

  android-example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Cache Node Modules
      uses: actions/cache@v5.0.5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v6.4.0
      with:
        node-version: '20'

    - name: Install root dependencies
      run: yarn install --frozen-lockfile

    - name: Install example dependencies
      run: yarn install --cwd example --frozen-lockfile

    - name: Build package
      run: yarn

    - name: Build Android example
      run: cd example/android && ./gradlew :app:assembleDebug

  ios-example:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Cache Node Modules
      uses: actions/cache@v5.0.5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v6.4.0
      with:
        node-version: '20'

    - name: Install root dependencies
      run: yarn install --frozen-lockfile

    - name: Install example dependencies
      run: yarn install --cwd example --frozen-lockfile

    - name: Build package
      run: CURRENT_ARCH=arm64 yarn

    - name: Install pods
      run: cd example/ios && RCT_NEW_ARCH_ENABLED=1 pod install

    - name: Build iOS example
      run: |
        xcodebuild \
          -workspace example/ios/ExperimentReactNativeClientExample.xcworkspace \
          -scheme ExperimentReactNativeClientExample \
          -configuration Debug \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator' \
          CODE_SIGNING_ALLOWED=NO \
          build
